facultyportal/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

facultyportal/main/routes.py
from flask import render_template, request, Blueprint
from facultyportal.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html")

facultyportal/posts/routes.py
from flask import (render_template, url_for, flash, 
                redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from facultyportal import db, mdb
from facultyportal.models import Post
from facultyportal.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route("/new/publication", methods=['GET', 'POST'])
@login_required
def new_publication():
    form = PostForm()
    if form.validate_on_submit():
        mdb.addPublication(current_user.email, form.title.data, form.content.data)
        flash('Your post has been created!', 'success')
        return redirect(url_for('users.profile'))
    return render_template('create_post.html', title='New Post', 
                            form=form, legend='New Post')


@posts.route("/new/award", methods=['GET', 'POST'])
@login_required
def new_award():
    form = PostForm()
    if form.validate_on_submit():
        mdb.addAward(current_user.email, form.title.data, form.content.data)
        flash('Your post has been created!', 'success')
        return redirect(url_for('users.profile'))
    return render_template('create_post.html', title='New Post', 
                            form=form, legend='New Post')


@posts.route("/new/other", methods=['GET', 'POST'])
@login_required
def new_other():
    form = PostForm()
    if form.validate_on_submit():
        mdb.addOther(current_user.email, form.title.data, form.content.data)
        flash('Your post has been created!', 'success')
        return redirect(url_for('users.profile'))
    return render_template('create_post.html', title='New Post', 
                            form=form, legend='New Post')


@posts.route("/post/bio/<string:biotitle>")
def post_bio(biotitle):
    # post = Post.query.get_or_404(post_id)
    post = mdb.getBio(current_user.email, biotitle)
    return render_template('post_bio.html', title=biotitle, post=post)


@posts.route("/post/<string:pubtitle>")
def post(pubtitle):
    # post = Post.query.get_or_404(post_id)
    post = mdb.getPublication(current_user.email, pubtitle)
    return render_template('post.html', title=pubtitle, post=post)

@posts.route("/post/award/<string:awardtitle>")
def post_award(awardtitle):
    # post = Post.query.get_or_404(post_id)
    post = mdb.getAward(current_user.email, awardtitle)
    return render_template('post_award.html', title=awardtitle, post=post)

@posts.route("/post/other/<string:othertitle>")
def post_other(othertitle):
    # post = Post.query.get_or_404(post_id)
    post = mdb.getOther(current_user.email, othertitle)
    return render_template('post_other.html', title=othertitle, post=post)

@posts.route("/bio/update/", methods=['GET', 'POST'])
@login_required
def update_bio():
    biotitle = request.args.get('biotitle')
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        mdb.updateBio(email=current_user.email, title=title, content=content)
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post_bio', biotitle=title))
    elif request.method == 'GET':
        form.title.data = biotitle
        try:
            post = mdb.getBio(current_user.email, biotitle)
            form.content.data = post['bio']['content']
        except:
            form.content.data = 'Bio Empty'
    return render_template('create_post.html', title='Update Post', 
                            form=form, legend='Update Post')


@posts.route("/publication/update/", methods=['GET', 'POST'])
@login_required
def update_post():
    pubtitle = request.args.get('pubtitle')
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        mdb.updatePublication(email=current_user.email, old_title=pubtitle, title=title, content=content)
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', pubtitle=title))
    elif request.method == 'GET':
        form.title.data = pubtitle
        print(pubtitle)
        post = mdb.getPublication(current_user.email, pubtitle)
        form.content.data = post['pubs'][0]['content']
    return render_template('create_post.html', title='Update Post', 
                            form=form, legend='Update Post')


@posts.route("/awards/update/", methods=['GET', 'POST'])
@login_required
def update_award():
    awardtitle = request.args.get('awardtitle')
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        mdb.updateAward(email=current_user.email, old_title=awardtitle, title=title, content=content)
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post_award', awardtitle=title))
    elif request.method == 'GET':
        form.title.data = awardtitle
        post = mdb.getAward(current_user.email, awardtitle)
        form.content.data = post['award'][0]['content']
    return render_template('create_post.html', title='Update Post', 
                            form=form, legend='Update Post')

@posts.route("/other/update/", methods=['GET', 'POST'])
@login_required
def update_other():
    othertitle = request.args.get('othertitle')
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        mdb.updateOther(email=current_user.email, old_title=othertitle, title=title, content=content)
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post_other', othertitle=title))
    elif request.method == 'GET':
        form.title.data = othertitle
        post = mdb.getOther(current_user.email, othertitle)
        form.content.data = post['other'][0]['content']
    return render_template('create_post.html', title='Update Post', 
                            form=form, legend='Update Post')


@posts.route("/post/delete", methods=['POST'])
@login_required
def delete_post():
    pubtitle = request.args.get('pubtitle')
    # if post.author != current_user:
    #     abort(403) # 403 means forbidden route
    mdb.deletePublication(email=current_user.email, title=pubtitle)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('users.profile'))


@posts.route("/award/delete", methods=['POST'])
@login_required
def delete_award():
    awardtitle = request.args.get('awardtitle')
    # if post.author != current_user:
    #     abort(403) # 403 means forbidden route
    mdb.deleteAward(email=current_user.email, title=awardtitle)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('users.profile'))


@posts.route("/other/delete", methods=['POST'])
@login_required
def delete_other():
    othertitle = request.args.get('othertitle')
    # if post.author != current_user:
    #     abort(403) # 403 means forbidden route
    mdb.deleteOther(email=current_user.email, title=othertitle)
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('users.profile'))

facultyportal/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from facultyportal import db, bcrypt, mdb
from facultyportal.models import User, Post
from facultyportal.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from facultyportal.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        mdb.createProfile(form.email.data)
        flash('Your account has been created! You can login now', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else :
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', 
                    image_file=image_file, form=form)


@users.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    form = UpdateAccountForm()
    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    profile = mdb.getProfile(current_user.email)
    return render_template('profile.html', title='Profile', 
                    image_file=image_file, form=form, posts=posts, profile=profile)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You can login now', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

facultyportal/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title> Faculty Portal - {{title}} </title>
    {% else %}
    <title> Faculty Portal </title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Faculty Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('users.profile') }}">Profile</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Faculty</h3>
                    <p class='text-muted'>Indian Institue of Techonology, Ropar
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Account Info</li>
                            <li class="list-group-item list-group-item-light">Publications</li>
                            <li class="list-group-item list-group-item-light">Awards</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

facultyportal/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="#">Guest Login</a>
        </small>
    </div>
{% endblock content %}

facultyportal/templates/post.html
{% extends "layout.html" %}
{% block content %}
<area class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
        </div>
        <h2><a class="article-title" href="#">{{ post['pubs'][0]['title'] }}</a></h2>
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post') }}?pubtitle={{title}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
        <p class="article-content">{{ post['pubs'][0]['content'] }}</p>
    </div>
</area>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModal">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Are you sure ?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post')}}?pubtitle={{title}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

facultyportal/templates/post_award.html
{% extends "layout.html" %}
{% block content %}
<area class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
        </div>
        <h2><a class="article-title" href="#">{{ post['award'][0]['title'] }}</a></h2>
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_award') }}?awardtitle={{title}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
        <p class="article-content">{{ post['award'][0]['content'] }}</p>
    </div>
</area>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModal">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Are you sure ?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_award')}}?awardtitle={{title}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

facultyportal/templates/post_bio.html
{% extends "layout.html" %}
{% block content %}
<area class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
        </div>
        <h2><a class="article-title" href="#">{{ post['bio']['title'] }}</a></h2>
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_bio') }}?biotitle={{title}}">Update</a>
        </div>
        <p class="article-content">{{ post['bio']['content'] }}</p>
    </div>
</area>

{% endblock content %}

facultyportal/templates/post_other.html
{% extends "layout.html" %}
{% block content %}
<area class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
        </div>
        <h2><a class="article-title" href="#">{{ post['other'][0]['title'] }}</a></h2>
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_other') }}?othertitle={{title}}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
        <p class="article-content">{{ post['other'][0]['content'] }}</p>
    </div>
</area>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteModal">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Are you sure ?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_other')}}?othertitle={{title}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

facultyportal/templates/profile.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">Dr. {{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>

    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#"> Professor </a>
            <small class="text-muted"> IIT Ropar </small>
        </div>
    </div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="biography-tab" data-toggle="tab" href="#biography" role="tab" aria-controls="biography" aria-selected="true">Biography</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="publication-tab" data-toggle="tab" href="#publication" role="tab" aria-controls="publication" aria-selected="false">Publications</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="awards-tab" data-toggle="tab" href="#awards" role="tab" aria-controls="awards" aria-selected="false">Awards</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="other-tab" data-toggle="tab" href="#other" role="tab" aria-controls="other" aria-selected="false">Others</a>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="biography" role="tabpanel" aria-labelledby="biography-tab">
            <a class="mr-2" href="{{ url_for('posts.update_bio') }}"> Update Biography </a>
                <area class="media content-section">
                  <div class="media-body">
                    <div class="article-metadata"></div>
                    <h2><a class="article-title" href="{{ url_for('posts.post_bio', biotitle=profile['bio']['title'] ) }}">{{ profile['bio']['title'] }}</a></h2>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_bio') }}?biotitle={{profile['bio']['title']}}">Update</a>

                    </div>
                    <p class="article-content">{{ profile['bio']['content'] }}</p>
                  </div>
                </area>
        </div>
        <div class="tab-pane fade" id="publication" role="tabpanel" aria-labelledby="publication-tab">
            <a class="mr-2" href="{{ url_for('posts.new_publication') }}"> Add new Publication </a>
            {% for pubs in profile['pubs'] %}
              {% if profile['email'] == current_user.email %}
                <area class="media content-section">
                  <div class="media-body">
                    <div class="article-metadata"></div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', pubtitle=pubs['title'] ) }}">{{ pubs['title'] }}</a></h2>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post') }}?pubtitle={{pubs['title']}}">Update</a>

                    </div>
                    <p class="article-content">{{ pubs['content'] }}</p>
                  </div>
                </area>
              {% endif %} 
            {% endfor %}
        </div>
        <div class="tab-pane fade" id="awards" role="tabpanel" aria-labelledby="awards-tab">
            <a class="mr-2" href="{{ url_for('posts.new_award') }}"> Add a new Award </a>
            {% for award in profile['award'] %}
              {% if profile['email'] == current_user.email %}
                <area class="media content-section">
                  <div class="media-body">
                    <div class="article-metadata"></div>
                    <h2><a class="article-title" href="{{ url_for('posts.post_award', awardtitle=award['title'] ) }}">{{ award['title'] }}</a></h2>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_award') }}?awardtitle={{award['title']}}">Update</a>

                    </div>
                    <p class="article-content">{{ award['content'] }}</p>
                  </div>
                </area>
              {% endif %} 
            {% endfor %}
        </div>
        <div class="tab-pane fade" id="other" role="tabpanel" aria-labelledby="other-tab">
            <a class="mr-2" href="{{ url_for('posts.new_other') }}"> Add new field </a>
            {% for other in profile['other'] %} 
              {% if profile['email'] == current_user.email %}
                <area class="media content-section">
                  <div class="media-body">
                    <div class="article-metadata"></div>
                    <h2><a class="article-title" href="{{ url_for('posts.post_other', othertitle=other['title'] ) }}">{{ other['title'] }}</a></h2>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_other') }}?othertitle={{other['title']}}">Update</a>

                    </div>
                    <p class="article-content">{{ other['content'] }}</p>
                  </div>
                </area>
              {% endif %} 
            {% endfor %}
        </div>
    </div>
</div>
<!-- Modal -->

{% endblock content %}